name: Build and push docker images for all services

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image for api
      with:
        image: michal299/sid-pg
        tags: api
        registry: docker.io
        dockerfile: api/Dockerfile
        directory: api/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image for generator
      with:
        image: michal299/sid-pg
        tags: generator
        registry: docker.io
        dockerfile: generator/Dockerfile
        directory: generator/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image for frontend service
      with:
        image: michal299/sid-pg
        tags: frontend
        registry: docker.io
        dockerfile: frontend/Dockerfile
        directory: frontend/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
