name: Build and push docker images for all services

on:
  push:
    branches:
      - master
      - composition # to delete

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image for api
      with:
        image: mcwynar/sid-pg
        tags: api
        registry: docker.io
        dockerfile: api/Dockerfile
        directory: api/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build and push docker image for generator
      with:
        image: mcwynar/sid-pg
        tags: generator
        registry: docker.io
        dockerfile: generator/Dockerfile
        directory: generator/
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
